name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Wait for SSH
        run: |
          for i in {1..10}; do
            if nc -z -w5 ${{ secrets.EC2_HOST }} 22; then
              echo "SSH is ready"
              exit 0
            fi
            sleep 5
          done
          echo "SSH connection timed out"
          exit 1

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ConnectTimeout=30 \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd ${{ secrets.EC2_PROJECT_PATH }} &&
            git pull &&
            npm ci &&
            npm run build &&
            pm2 restart portfolio || pm2 start npm --name 'portfolio' -- start
          "
